---
title: 'LA.4: Working with Data (10 points)'
pagetitle: "COMM 3710: LA.4"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
urlcolor: blue
---

# Resources
- Before starting this assignment, watch the following video: https://youtu.be/b9Bh3K5bi0I. It covers data management processes in R. Once again, keep this link handy as you may need to watch the video several times.
- Revisit the [R Help Guide](https://rpubs.com/yesun/Comm3710_helpwithR) if necessary. 

---

# Data 

For this assignment, we will still be working with the [Health Evaluation and Linkage to Primary Care (HELP) data set](https://yesuncomm.github.io/comm3710/files/HELP.csv) as in LA.3. If necessary, review the full codebook (explanation of variables) in [LA.3](https://yesuncomm.github.io/comm3710/LA/LA.3.html). 

For this assignment, we'll be working with these variables specifically: 

* `mcs`: SF-36 Mental Component Score (measured at baseline; lower scores indicate worse status)
* `g1b`: whether patient experienced serious thoughts of suicide in last 30 days (measured at baseline; a categorical variable with levels "no" and "yes")
* `homeless`: housing status: a categorical variable with levels "housed" and "homeless"

---

# Instructions
1. Load in the [HELP data set](https://yesuncomm.github.io/comm3710/files/HELP.csv) in R. 
<details>
<summary>Hint</summary>

   If necessary, review how you imported/read the .csv data in [LA.3](https://yesuncomm.github.io/comm3710/LA/LA.3.html). Remember that you can name this object anything you like. In the hints below, I'll keep using `helpdata` as the name of the data object.
</details>
<br>

2. Focuses on the variable `mcs` --  the "mental component score" of a patient. Patients with a mental component score (`mcs`) less than 20 are thought to be at extreme risk of returning to the detoxification unit within the next 12 months.   

   2a. First, check the frequency of `mcs` (review how you ran frequency in LA.3) and report its range (i.e, the smallest and largest values of `mcs`). (Plesae note: you do not need to turn in the frequency table for `mcs`, which is too large to be included in the PDF document.)    
        
   2b. Suppose we are only interested in whether patients are at extreme risk (i.e., with `mcs` < 20) or not (i.e., with `mcs` >= 20), instead of their specific `mcs` scores. 
   
   Based on `mcs`, create a new variable in the same data set called `ExtremeMCS` that contains only these two categories (i.e., whether the patient is at extreme risk or not). Code `ExtremeMCS` as `1` if a patient is at extreme risk and `0` otherwise. 

   <details>
   <summary>Hint</summary>
   An important part of data management processes (covered in the linked video) is to create new variables based on existing ones. In this question, we can get at the new variable `ExtremeMCS` through the following process:  
   
   1) The goal is to create a variable and add it to the data set, in other words, to create an object in R with the generic form `DataFrame$NewVariable` (i.e., a new variable attached to the existing data set). In the example of this question, we will create this object as `helpdata$ExtremeMCS <-    `  
   
   2) This new variable `ExtremeMCS` takes on the value of either `1` or `0`. We already know that to assign a value to an object, it generally looks like (depicting the thought process, not the complete code): 
   
      ```
         helpdata$ExtremeMCS             <- 1
         helpdata$ExtremeMCS             <- 0
      ```

   3) Next, we need to specify the condition under which `1` or `0` is assigned to the new variable. According to the instruction, `1` is for the "at extreme risk" category (i.e., `mcs` < 20). As you have seen in the examples in the video, such conditions can be specified by using `[ ]`. Below is the code for one category of `ExtremeMCS`. You can complete the code for the other category on your own.    
   
       ```
         helpdata$ExtremeMCS[helpdata$mcs < 20] <- 1   
         helpdata$ExtremeMCS[                 ] <- 0  
         ## Created variable ExtremeMCS: 1 = "at extreme risk (mcs < 20)"; 
         ## 0 = "not at extreme risk (mcs >= 20)"
         
      ``` 
   <details>
   <summary>Alternative (if you are interested)</summary>  
   This is not covered in the video. It is an easier alternative with the `ifelse` command. 
   
         ```
         helpdata$ExtremeMCS <- ifelse(helpdata$mcs < 20, 1, 0)
         
         ```
   Figure out what the arguments (the text and numbers within the parentheses) in the `ifelse` function mean by running the command line `?ifelse` and reading the documentation.
   </details> 
   <br>


   2c. Make a frequency table for `ExtremeMCS` and answer the question: How many patients are in the "at extreme risk" category? <!--91-->
   
3. Make a new variable `SuicidalThought` based on the variable `g1b`. Have `1` indicate a patient has had suicidal thoughts and `0` indicate they have not. 

   Make a frequency table for `SuicidalThought` and answer the question: What percentage of patients have experienced suicidal thoughts? <!--28.0%-->

   <details>
   <summary>Hint</summary>

   You can use the same logic from Q2 to create this variable. Note that you'll first want to check what the variable `g1b` consists of in the data set -- run frequency, and you can also use `head(helpdata$g1b)` to take a peek at the first 6 rows of the data. Getting to know the categories or values of the variable will help you correctly specify the conditions when creating the new variable (more hint: the `substance` variable in Q2c in LA.3).  
   </details>
<br>

4. Make a new variable `HomelessStatus` based on the variable `homeless`. Have 1 indicate that a patient is homeless and 0 indicate that they are housed. 

   Make a frequency table for `HomelessStatus` and answer the question: What percentage of patients are homeless? 

   <details>
      <summary>Hint</summary>

   See hints from Q2 and Q3 to create this variable.
   </details>
   <br>
   
5. Suppose we want to assess the overall risk a patient has to return to the detoxification unit and `ExtremeMCS`, `SuicidalThought`, and `HomelessStatus` are considered risk factors. 

   Construct a new variable called `RiskTotal` which computes the number of risk factors a particular patient has. That is, make it a sum of these 3 variables. After creating the variable, make a frequency table for `RiskTotal` and answer the question: What percentage of patients in the study have fewer than 3 risk factors? <!--94.9%-->
   
   <details>
   <summary>Hint</summary>

   You want to create a new variable called `RiskTotal`, which is the sum of `ExtremeMCS`, `SuicidalThought`, and `HomelessStatus`. The most straightforward way of doing it follows this general formula--
   
   ```
   Dataframe$NewVariable <- Dataframe$Var1 + Dataframe$Var2 + Dataframe$Var3 
   ```
   
   <details>
      <summary>Alternative (if you are interested)</summary>  
   Like most things in R, there are many other ways to do this. Another way to do this is to `transform` the data:
  
   ```
   helpdata <- transform(helpdata, RiskTotal = ExtremeMCS + SuicidalThought + HomelessStatus)
   ```
   For help with `transform`, type `?transform` into the Console and read the documentation.
</details>
<br>


**Submit the following on Canvas:**   
   (a) A **.R file** containing the code used to complete this assignment. This document should include comments that explain your commands.  
   (b) A **PDF file** containing the frequency tables and answers to each question--clearly label the answers with the question number.
   